stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Start docker build"
    - docker build -t booking-api-image .

deploy-job:
  stage: deploy
    - echo "Deploying application..."
    - docker compose up -d