stages:
  - build
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${ENV_TEST} .env-test
  script:
    - echo "Start docker build"
    - docker build -t booking-api-image .

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker compose -f docker-compose-ci.yml up -d