services:
  booking_back_service:
    container_name: 'booking_back'
    image: booking-api-image:latest
    networks:
      - myNetwork

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    image: booking-api-image:latest
    networks:
      - myNetwork
    command: "celery --app=src.tasks.celery_app:celery_app_task_instance worker -l INFO"

  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    image: booking-api-image:latest
    networks:
      - myNetwork
    command: "celery --app=src.tasks.celery_app:celery_app_task_instance beat -l INFO"

networks:
  myNetwork:
    external: true