"""rooms for hotel migration

Revision ID: b3cc2114c277
Revises: 2a3fabddc284
Create Date: 2024-11-25 21:04:49.958865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cc2114c277'
down_revision: Union[str, None] = '2a3fabddc284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hotels', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotels', type_='unique')
    # ### end Alembic commands ###
